config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :admin do
    resources :users
  end
  root to: 'tasks#index'
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :label_tags
  has_many :which_tasks, through: :label_tags, source: :task
  #.which_tasksメソッドで、紐づくtaskを呼び出せる
end

app/models/label_tag.rb
class LabelTag < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/task.rb
class Task < ApplicationRecord
  validates :task_name, presence: true
  scope :important, -> {order(priority: :asc)}
  scope :latest, -> {order(created_at: :desc)}
  scope :expired, -> {order(deadline: :asc)}
  scope :search, -> (params) {where('(task_name LIKE ?) AND (status LIKE ?)',
                                  "%#{params[:task][:task_name_key]}%",
                                  "%#{params[:task][:status_key]}%")}



  # scope :search, -> (params) {where('(task_name LIKE ?) AND (status LIKE ?) AND (which_label_ids LIKE ?)',
  #                                   "%#{params[:task][:task_name_key]}%",
  #                                   "%#{params[:task][:status_key]}%",
  #                                   "%#{params[:task][:which_label_ids]}%")}

  enum priority: { not_entered: 0, high: 1, medium: 2, low: 3 }
  belongs_to :user
  has_many :label_tags, dependent: :destroy
  has_many :which_labels, through: :label_tags, source: :label
  #.which_labelsメソッドで、紐づくlabelを呼び出せる
  # accepts_nested_attributes_for :label_tags
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :user_name, presence: true
  validates :email, presence: true, uniqueness: true

  before_destroy :do_not_destroy_last_admin
  has_many :tasks, dependent: :destroy


  def do_not_destroy_last_admin
    if self.admin? && User.where(admin: :true).count == 1
      throw :abort
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  skip_before_action :login_required
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :destroy_myself, only: [:destroy]


  def index
    if current_user.admin?
      @users = User.select(
        :id, :user_name, :email, :admin, :created_at, :updated_at)
    else
      redirect_to root_path,
                  notice: "管理者権限がありません"

    end
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id unless current_user
      # ↑管理ユーザーが新しいユーザを登録した際、他のユーザーのセッションに切り替わらないようにする記述
      redirect_to admin_user_path(@user),
                  notice: "ユーザー「#{@user.user_name}」を登録しました。"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path(@user),
                  notice: "ユーザー「#{@user.user_name}」を更新しました。"
    else
      render :new
    end
  end

  def destroy
    @user.destroy

    redirect_to admin_users_url,
                notice: "ユーザー「#{@user.user_name}」を削除しました。"
  end

  private

  def user_params
    params.require(:user).permit(
      :user_name, :email, :password, :password_confirmation, :admin)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def destroy_myself
    if @user == current_user
      redirect_to admin_users_url,
                  notice: "自分自身を削除することは出来ません。"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_path unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required

  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: I18n.t('now_logged')
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: I18n.t('now_logout')
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    if params[:sort_priority]
      # @tasks = Task.order(priority: :asc)
      @tasks = current_user.tasks.important
    elsif params[:sort_expired]
      # @tasks = Task.order(deadline: :asc)
      @tasks = current_user.tasks.expired
    elsif params[:task] == nil
      # @tasks = Task.order(created_at: :desc)
      @tasks = current_user.tasks.latest
    elsif params[:task][:search]
      @tasks = current_user.tasks.search(params)
      # @tasks = Task.where('task_name LIKE ? AND status LIKE ?', "%#{params[:task][:task_name_key]}%", "%#{params[:task][:status_key]}%")
      # @tasks = Task.search(params[:task][:task_name_key],params[:task][:status_key])
      if params[:task][:which_label_ids].present?
        label = LabelTag.where(label_id: params[:task][:which_label_ids]).pluck(:task_id)
        @tasks = current_user.tasks.search(params)
        @tasks = @tasks.where(id: label)
      end
    end
    @tasks = @tasks.page(params[:page]).per(7)
  end

  def new
    @task = Task.new
    @labels = Label.all
    # @task.label_tags.build
  end

  def create
    @task = current_user.tasks.new(task_params)
    # label_note = LabelTag.new(label_params)
    # @task.label_tags = label_tags(label_ids: label_note)
    if @task.save # 親要素を保存かけてあげることで自動で子要素も保存されます！
      redirect_to root_path, notice: "タスクが保存されました！"
    else
      render 'new'
    end
    # binding.pr
    # @label_tags = LabelTag.create(label_id:(params[:label_tags]), task_id: @task.id)
  end

  def show
  end

  def edit
    @labels = Label.all
  end

  def update
    if @task.update(task_params)
      redirect_to root_path, notice: "タスクを編集しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @task.destroy
    redirect_to root_path, notice: "タスクを削除しました！"
  end

  private

  def task_params
    params.require(:task).permit(
      :task_name,
      :note,
      :deadline,
      :status,
      :priority,
      which_label_ids: []
    )
  end


  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/admin/users/_form.html.erb
<%= form_with(model: [:admin, @user], local: true) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> </h2>
      <ul>

        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="admin_form_content">
    <%= f.label :user_name %>
    <%= f.text_field :user_name, class: 'form-control' %>

    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
    <br>

    <%= f.label :admin, class: "form-check-label" %>
    <%= f.check_box :admin, {}, class: 'form-check-input' %>
    <br><br>


    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, id: 'password_confirmation', class: 'form-control' %>

    <%= f.submit t('create') %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1><%= t('edit') %> </h1>

<%= render 'admin/users/form'%>

app/views/admin/users/index.html.erb
<h1>ユーザー一覧</h1>
<p><%= notice %></p>

<div class="table">
  <table>
    <tr>
      <th><%= t('user_name') %></th>
      <th><%= t('email') %></th>
      <th><%= t('admin') %></th>
      <th><%= t('created_at') %></th>
      <th><%= t('updated_at') %></th>
      <th><%= t('task_count') %></th>

    </tr>

    <% @users.each do |user| %>
      <tr>
        <td><%= user.user_name %></td>
        <td><%= user.email %></td>
        <td><%= user.admin? ? "あり":"なし" %></td>
        <td><%= user.created_at %></td>
        <td><%= user.updated_at %></td>
        <td><%= user.tasks.count %></td>
        <td><%= link_to t('to_note'), admin_user_path(user) %></td>
        <td><%= link_to t('edit'), edit_admin_user_path(user) %></td>
        <td><%= link_to t('destroy'), [:admin, user],method: :delete,data:{confirm:I18n.t('confirm')} %></td>
      </tr>
    <% end %>
  </table>
</div>
<%#= paginate @tasks %>
<%= link_to t('new'), new_admin_user_path %>

app/views/admin/users/new.html.erb
<h1> <%= t('user_entry') %> </h1>


<%= render 'admin/users/form'%>

app/views/admin/users/show.html.erb
<% if (@user.id == current_user.id) || (current_user.admin?) %>
  <h2><%= t('user_name') %>：<%= @user.user_name %></h2>
  <p><%= t('email') %>：<%= @user.email %></p>
  <p><%= t('admin') %>：<%= @user.admin? ? "あり" : "なし" %></p>
  <%= link_to t('edit'), edit_admin_user_path(@user) %>
  <%= link_to t('destroy'), [:admin, @user], method: :delete, data: {confirm: I18n.t('confirm')} %>
  <%= link_to t('index'), root_path %>
<% else %>
  <p>権限がありません</p>
<% end %>


<% if current_user.admin? %>
  <div class="table">
    <table>
      <tr>
        <th><%= t('task_name') %></th>
        <th><%= t('note') %></th>
        <th><%= t('created_at') %></th>
        <th><%= t('deadline') %></th>
        <th><%= t('status') %></th>
        <th><%= t('priority') %></th>
        <th><%= t('label') %></th>
      </tr>

      <% @user.tasks.each do |task| %>
        <tr>
          <td><%= task.task_name %></td>
          <td><%= task.note %></td>
          <td><%= task.created_at %></td>
          <td><%= task.deadline %></td>
          <td><%= task.status %></td>
          <th><%= task.priority_i18n %></th>
          <td><%= task.which_labels.count %></td>
          <td><%= link_to t('to_note'), task_path(task.id) %></td>
          <td><%= link_to t('edit'), edit_task_path(task.id) %></td>
          <td><%= link_to t('destroy'), task_path(task.id), method: :delete, data: {confirm: I18n.t('confirm')} %></td>
        </tr>
      <% end %>
    </table>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManyoTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header id="header">
    <div class="logo">
      <h2>ManyoTask</h2>
    </div>
    <% if current_user %>
      <ul>
        <li><%= link_to t('index'), tasks_path %></li>
        <% if current_user.admin? %>
          <li><%= link_to t('activerecord.models.user'), admin_users_path %></li>
        <% end %>
        <li><%= link_to t('logout'), logout_path, method: :delete %></li>
<!--        <li><h4><%#= current_user.user_name %></h4>-->
        <li><%= link_to current_user.user_name, admin_user_path(current_user.id) %></li>

      </ul>
    <% else %>
      <ul>
        <li><%= link_to t('sigin_up'), new_admin_user_path %></li>
        <li><%= link_to t('login'), login_path %></li>
      </ul>
    <% end %>

  </header>

  <%= yield %>
  <footer>
    <p>あらいあゆみ</p>
    <p>2019.6</p>
  </footer>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> </h2>
      <ul>

        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="task_content">

    <%= form.label :task_name %>
    <%= form.text_field :task_name %>
    <%= form.label :note %>
    <%= form.text_field :note %>
    <%= form.label :deadline %>
    <%= form.datetime_select :deadline %>
    <%= form.label :status %>
    <%= form.select :status, [[t('done'), t('done')],
                              [t('not_started'), t('not_started')],
                              [t('in_progress'), t('in_progress')],
                              [t('hold'), t('hold')]]
    %>
    <%= form.label :priority %>
    <%= form.select :priority, Task.priorities_i18n.invert, {} %>
    <br>
    <p><%= t('label') %></p>
    <% @labels.each do |label| %>
      <%= form.check_box :which_label_ids, {
          multiple: true,
          #multiple:複数チェックボックスで配列形式のパラメータを送れる
          checkd: label[:checked],
          #:checked	チェックボックスのチェックの有無
          disabled: label[:disabled],
          #:disabled	フォームの項目の利用禁止
          include_hidden: false}, #チェックが入っていない時、何も送らない
                         label[:id] %>

      <%= label.label_name %>
    <% end %>
    <br><br>
    <%= form.submit t('create') %>
  </div>
<% end %>


<br>
<%= link_to t('index'), root_path %>

app/views/tasks/edit.html.erb
<h2><%= t('edit') %></h2>

<%= render 'form' %>

app/views/tasks/index.html.erb
<h1><%= t('index') %></h1>
<p><%= notice %></p>
<%= form_with(model: Task.new, method: :get, local: true) do |f| %>
  <%= f.label :task_name_key, t('sarch_task_name') %>
  <%= f.text_field :task_name_key %>
  <%= f.label :status_key, t('sarch_status') %>
  <%= f.select :status_key, [[t('done'), t('done')],
                             [t('not_started'), t('not_started')],
                             [t('in_progress'), t('in_progress')],
                             [t('hold'), t('hold')]],
               prompt: ''
  %>
  <%= f.label :which_label_ids, t('sarch_label') %>
  <%= f.select :which_label_ids, Label.all.map{|t| [t.label_name, t.id]}, { include_blank: true } %>

  <%= f.hidden_field :search, value: 'true' %>
  <%= f.submit t('search') %>
  <%#= link_to 'Clear', forecasts_path %>
<% end %>
<%= link_to t('sort_priority'), root_path(sort_priority: "true") %>
<%= link_to t('sort_deadline'), root_path(sort_expired: "true") %>
<%= link_to t('sort_created_at'), tasks_path %>

<div class="table">
  <table>
    <tr>
      <th><%= t('task_name') %></th>
      <th><%= t('note') %></th>
      <th><%= t('created_at') %></th>
      <th><%= t('deadline') %></th>
      <th><%= t('status') %></th>
      <th><%= t('priority') %></th>
      <th><%= t('label') %></th>
    </tr>

    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.task_name %></td>
        <td><%= task.note %></td>
        <td><%= task.created_at.strftime('%Y年%m月%d日 %H:%M:%S') %></td>
        <td><%= task.deadline.strftime('%Y年%m月%d日 %H:%M:%S') %></td>
        <td><%= task.status %></td>
        <th><%= task.priority_i18n %></th>
        <td><%= task.which_labels.count %></td>
        <td><%= link_to t('to_note'), task_path(task.id) %></td>
        <td><%= link_to t('edit'), edit_task_path(task.id) %></td>
        <td><%= link_to t('destroy'), task_path(task.id), method: :delete, data: {confirm: I18n.t('confirm')} %></td>
      </tr>
    <% end %>
  </table>
</div>
<%= paginate @tasks %>
<%= link_to t('new'), new_task_path %>

app/views/tasks/new.html.erb
<h2><%= t('new') %></h2>

<%= render 'form' %>

app/views/tasks/show.html.erb
<h2><%= t('task_name') %>：<%= @task.task_name %></h2>
<p><%= t('note') %>：<%= @task.note %></p>
<p><%= t('deadline') %>：<%= @task.deadline %></p>
<p><%= t('status') %>：<%= @task.status %></p>
<p><%= t('priority') %>：<%= @task.priority %></p>
<p><%= t('label') %>：
  <% @task.which_labels.each do |l| %>
    <%= l.label_name %>,
  <% end %>
</p>


<%= link_to t('index'), root_path %>